kodadot/snek

package-lock.json
package.json
src/server-extension/model/count.model.ts
src/server-extension/model/offerStats.model.ts
src/server-extension/query/activeWallets.ts
src/server-extension/query/offerStats.ts
src/server-extension/resolvers/index.ts
src/server-extension/resolvers/offerStatsResolver.ts
src/server-extension/resolvers/walletResolver.ts
src/server-extension/utils.ts

feat: activeWallets / offerStats #30, #29

---

src/mappings/index.ts

fix: no emit via buy and accept offer

---

.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/subsquid.yml

- :memo: pull request template for PRs
- :construction_worker: added autopulish for snek
- :green_heart: snekk is a special

AutoPublish + PR Template

---

db/migrations/1660297956736-Data.js
schema.graphql
src/model/generated/collectionEntity.model.ts
src/model/generated/nftEntity.model.ts

- 🧐 added indices to name
- 🏷️  generated
- 🗃️ Added indexes for the name

Indexes for the Snek's names

---

src/server-extension/query/event.ts

:bug: LastEvent resolver should return something for the name

---

src/server-extension/query/event.ts

RELEASE 003

---

src/server-extension/model/event.model.ts
src/server-extension/query/event.ts

- related with https://github.com/kodadot/rubick/pull/129
- related with https://github.com/kodadot/nft-gallery/issues/3797
- related with https://github.com/kodadot/nft-gallery/pull/3786

🔧 event animation_url

---

src/server-extension/model/event.model.ts
src/server-extension/query/event.ts

release(003): Animation url for last events

---

.env
src/processor.ts

launch the snek

---

Makefile
package.json

- ✨ series resolver
- add collection in lastEvent
- 🔧 cached query
- 🔧 pnpm lock?
- 🔧 query & resolver
- 🔧 series db migration
- Update README.md
- 🔧 seriesInsightTable defaultValue & type
- 🔧 better defaultValue
- launch the snek
- :top: :package:
- :bug: changes in typeorm
- :wrench: config for rococo and prod
- :robot: correct justfile
- :squid: codegen
- :wrench: what is ETA on mainnet kodadot going live?
- :snake: Rococo
- :robot: prod
- :bug: migrate

release(004) can sneks do something?

---

src/mappings/assetRegistry/getters.ts

- :bug: working asset registry
- :bug: working asset registry

release(005) Snek cannot help you if you do not save the code

---

src/processor.ts

Deployed `snek` instead of `bsx` for 005

:bug: mom can we have prod?

---

src/mappings/index.ts

🔧 updateCache on Transfer, Burn, Buy & Offer

---

src/server-extension/query/event.ts

🔧 lastEvent check collection name not null

---

src/server-extension/model/event.model.ts
src/server-extension/query/event.ts
src/server-extension/resolvers/collectionEvent.ts
src/server-extension/resolvers/index.ts

✨ collection buyEventStatsById

---

db/migrations/1666944897549-Data.js
schema.graphql
src/mappings/index.ts
src/model/generated/collectionEntity.model.ts

✨ collection supply

---

src/mappings/index.ts

This change need to reindex data

🔧 handleTokenTransfer nftentity updatedAt

---

src/mappings/index.ts

on event interaction "BUY" price is null (or 0)
because `Number.toString()` is not working 
I've checked console log, this will need to run indexer again
None.

🔧 handleTokenBuy price string

---

.github/workflows/subsquid.yml
src/environment.ts
src/processor.ts

- :zap: use environment variables
- :green_heart: automatized deploy of snek
- :zap: use DEV if env.VERSION is not defined
Introducing ENV variable VERSION so we do not deploy bad urls by mistake

enviro snek

---

package-lock.json
package.json

Update MinIPFS. credits to @preschian

Update MinIPFS to use Promise.any

---

src/server-extension/query/event.ts

fix: check name and image is not null

---

src/mappings/utils/cache.ts

release-005 quickfix

---

src/mappings/utils/helper.ts
src/server-extension/model/spotlight.model.ts
src/server-extension/query/event.ts
src/server-extension/resolvers/collectionEvent.ts
src/server-extension/resolvers/event.ts
src/server-extension/resolvers/series.ts
src/server-extension/resolvers/spotlight.ts
src/server-extension/resolvers/walletResolver.ts

:soap: Mr. cl0w broke 3 bottles

---

src/mappings/utils/getters.ts

```
/^\/^\
_|__|  O|
\/     /~     \_/ \
\____|__________/  \
\_______      \
`\     \                 \
|     |                  \
/      /                    \
/     /                       \\
/      /                         \ \
/     /                            \  \
/     /             _----_            \   \
/     /           _-~      ~-_         |   |
(      (        _-~    _--_    ~-_     _/   |
\      ~-____-~    _-~    ~-_    ~-_-~    /
~-_           _-~          ~-_       _-~
~--______-~                ~-___-~
```

:snake: all the smol sneks

---

src/mappings/index.ts
src/processor.ts

This PR will disable OFFERS on SNEK and BSX

:snek: :ambulance: disabled offers

---

package-lock.json
package.json

:snake: Subscribe to snek

---

.gitignore
package-lock.json
package.json
src/mappings/index.ts
src/mappings/utils/getters.ts
src/mappings/utils/types.ts
src/processor.ts

- :arrow_up: @subsquid deps
- :see_no_evil: SQL Dumps
- :zap: reenable offers

Enable Offers and use Koda Images

---

src/mappings/index.ts
src/mappings/utils/metadata.ts

- :zap: handle metadata view properly
- :zap: ensure metadta URI

Media for Liquidity mining

---

FAQ.md
README.md

Fix: typos

---

src/mappings/utils/cache.ts

:zap: updated metadata every 10 minutes

---

package-lock.json
package.json
src/mappings/utils/metadata.ts

Metadata Cache

---

src/mappings/utils/getters.ts

Closes #164
Fix kodadot/nft-gallery#5266
Indexing is much more longer now

🔧 metadata collection entity

---

.env
src/environment.ts
src/processor.ts

@vikiival hello sirr, wen upcoming release?

⬆️ update snek endpoint

---

schema.graphql
src/mappings/assetRegistry/getters/basilisk.ts
src/mappings/assetRegistry/index.ts
src/mappings/assetRegistry/types.ts
src/model/generated/assetEntity.model.ts
src/types/basilisk/events.ts
src/types/basilisk/v101.ts

- :squid: typegen basilisk
- :bug: v101 failing
- :alien: deposit
- :zap: mark miimal existential deposit for token

bsx untyped

---

db/migrations/1693401033913-Data.js

:card_file_box: deposit

---

db/migrations/1693406570820-Data.js
src/mappings/assetRegistry/index.ts

- :bug: safe assign
- :card_file_box: like wtf

another snek fixes because i sit in oebb and i can

---

src/mappings/assetRegistry/getters/snek.ts
src/types/snek/events.ts
src/types/snek/v97.ts

- :squid: typegen basilisk
- :bug: AssetRegistry.Updated v97 on snek
AssetRegistry.Updated was updated to v97 on Snek

stuck snek

---

db/migrations/1695821906886-Data.js
schema.graphql
snek.yaml
src/model/generated/collectionEntity.model.ts
src/model/generated/nftEntity.model.ts

- Close #195
- :wrench: scale config for small snek

Config for snek

---

snek.yaml
src/mappings/index.ts

- :wrench: sneck v2
- :bug: null value in column "owner_count" of relation "collection_entity" violates not-null constraint

just a lot of sneck
